# Generated by Django 4.2.24 on 2025-09-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('m2_construidos', models.FloatField(default=0)),
                ('m2_totales', models.FloatField(default=0)),
                ('estacionamientos', models.PositiveIntegerField(default=0)),
                ('habitaciones', models.PositiveIntegerField(default=0)),
                ('banos', models.PositiveIntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo_inmueble', models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('PARCELA', 'Parcela')], max_length=20)),
                ('arrendado', models.BooleanField(default=False)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.comuna')),
            ],
        ),
    ]
