# Generated by Django 4.2.24 on 2025-09-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_solicitudarriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default='imagenes_inmueble/casa-sin-imagen', upload_to='imagenes_inmueble/'),
        ),
    ]
