# Generated by Django 4.2.24 on 2025-09-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_inmueble_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
