# Generated by Django 4.2.24 on 2025-09-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='zona',
            field=models.CharField(choices=[('NORTE', 'Zona Norte'), ('CENTRO', 'Zona Centro'), ('SUR', 'Zona Sur')], max_length=10),
        ),
    ]
