# Generated by Django 4.2.24 on 2025-09-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_region_zona'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.comuna'),
        ),
    ]
